DROP TABLE IF EXISTS holdingejb;
DROP TABLE IF EXISTS accountprofileejb;
DROP TABLE IF EXISTS accountejb;
DROP TABLE IF EXISTS quoteejb;
DROP TABLE IF EXISTS keygenejb;
DROP TABLE IF EXISTS orderejb;


CREATE TABLE holdingejb (PURCHASEPRICE DECIMAL(14, 2), HOLDINGID INTEGER NOT NULL, QUANTITY DOUBLE NOT NULL, PURCHASEDATE TIMESTAMP, ACCOUNT_ACCOUNTID INTEGER, QUOTE_SYMBOL VARCHAR(250));

#ALTER TABLE HOLDINGEJB ADD CONSTRAINT PK_HOLDINGEJB PRIMARY KEY (HOLDINGID)

CREATE TABLE accountprofileejb (ADDRESS VARCHAR(250), PASSWD VARCHAR(250), USERID VARCHAR(250) NOT NULL, EMAIL VARCHAR(250), CREDITCARD VARCHAR(250), FULLNAME VARCHAR(250));

#ALTER TABLE ACCOUNTPROFILEEJB ADD CONSTRAINT PK_ACCOUNTPROFILE2 PRIMARY KEY (USERID)

CREATE TABLE quoteejb (LOW DECIMAL(14, 2), OPEN1 DECIMAL(14, 2), VOLUME DOUBLE NOT NULL, PRICE DECIMAL(14, 2), HIGH DECIMAL(14, 2), COMPANYNAME VARCHAR(250), SYMBOL VARCHAR(250) NOT NULL, CHANGE1 DOUBLE NOT NULL);

#ALTER TABLE QUOTEEJB ADD CONSTRAINT PK_QUOTEEJB PRIMARY KEY (SYMBOL)

CREATE TABLE keygenejb (KEYVAL INTEGER NOT NULL, KEYNAME VARCHAR(250) NOT NULL);

#ALTER TABLE KEYGENEJB ADD CONSTRAINT PK_KEYGENEJB PRIMARY KEY (KEYNAME)

CREATE TABLE accountejb (CREATIONDATE TIMESTAMP, OPENBALANCE DECIMAL(14, 2), LOGOUTCOUNT INTEGER NOT NULL, BALANCE DECIMAL(14, 2), ACCOUNTID INTEGER NOT NULL, LASTLOGIN TIMESTAMP, LOGINCOUNT INTEGER NOT NULL, PROFILE_USERID VARCHAR(250));

#ALTER TABLE ACCOUNTEJB ADD CONSTRAINT PK_ACCOUNTEJB PRIMARY KEY (ACCOUNTID)

CREATE TABLE orderejb (ORDERFEE DECIMAL(14, 2), COMPLETIONDATE TIMESTAMP, ORDERTYPE VARCHAR(250), ORDERSTATUS VARCHAR(250), PRICE DECIMAL(14, 2), QUANTITY DOUBLE NOT NULL, OPENDATE TIMESTAMP, ORDERID INTEGER NOT NULL, ACCOUNT_ACCOUNTID INTEGER, QUOTE_SYMBOL VARCHAR(250), HOLDING_HOLDINGID INTEGER);

#ALTER TABLE ORDEREJB ADD CONSTRAINT PK_ORDEREJB PRIMARY KEY (ORDERID)

#ALTER TABLE HOLDINGEJB VOLATILE
#ALTER TABLE ACCOUNTPROFILEEJB VOLATILE
#ALTER TABLE QUOTEEJB VOLATILE
#ALTER TABLE KEYGENEJB VOLATILE
#ALTER TABLE ACCOUNTEJB VOLATILE
#ALTER TABLE ORDEREJB VOLATILE

#CREATE INDEX ACCOUNT_USERID ON accountejb(PROFILE_USERID);
#CREATE INDEX HOLDING_ACCOUNTID ON holdingejb(ACCOUNT_ACCOUNTID);
#CREATE INDEX ORDER_ACCOUNTID ON orderejb(ACCOUNT_ACCOUNTID);
#CREATE INDEX ORDER_HOLDINGID ON orderejb(HOLDING_HOLDINGID);
#CREATE INDEX CLOSED_ORDERS ON orderejb(ACCOUNT_ACCOUNTID,ORDERSTATUS);
  

